### ISSUE TITLE
Implement search

### ISSUE THREAD

**Issue by knownasilya** [ember-learn/guias#15]
I think the talk was to use Algolia (current service). @acorncom mentioned he had some alpha software for Algolia integration.

**Comment by knownasilya** [comment]
Blocked on @acorncom extracting his algolia addon 😉

**Comment by acorncom** [comment]
@knownasilya I've been looking at this today and it's getting a bit more involved.  My original work (and thought for an add-on) was based around using the Algolia-lite client, but ideally we'd use the Docsearch client for Ember sites (it's in essence a simplified wrapper on top of the Algolia-lite client): https://github.com/algolia/docsearch/blob/master/src/lib/DocSearch.js

But the docsearch wrapper includes templating, event handling, etc that made life simpler for `guides.emberjs.com` but likely to make it more difficult within an Ember app (unless we just wrap the docsearch JS file and call it a day).  Thoughts?

**Comment by knownasilya** [comment]
We probably want to use https://github.com/algolia/algoliasearch-client-js and build our own UI using something like ember-power-select.

**Comment by acorncom** [comment]
Confirmed.  There were two things that struck me as potential sources of breaking changes in the future:

- `appId` is hard-coded in their file (https://github.com/algolia/docsearch/blob/master/src/lib/DocSearch.js#L36).  Because they publish an NPM package, that seems unlikely to change.  But their suggested usage when they sent me stuff was to use a CDN package.  If they decide to roll that app id ...
- their backend data format is tied in pretty tightly to that file (https://github.com/algolia/docsearch/blob/master/src/lib/DocSearch.js#L177-L230).  There again, because of the NPM module, we're likely to be ok but if they change things on their end we might be caught unawares ...

How concerned do you think we should be there?  I'm inclined to risk it (as we're aiming to make publishing all docs simpler than it is now, so updates if needed shouldn't be as painful)

**Comment by knownasilya** [comment]
That's just a default value for `appId`, which is overwritten by a users options hash.

**Comment by acorncom** [comment]
Actually, it isn't.  If you take a look at this, they only check these values (https://github.com/algolia/docsearch/blob/master/src/lib/DocSearch.js#L49) and this is the usage they recommend: https://github.com/emberjs/guides/blob/master/source/javascripts/app/docsearch.js.erb#L19-L27

All folks using docsearch use a common index on Algolia's end
